# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  # build in /build folder
  # go version : 1.20.2
  # go os : ubuntu-latest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.20.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2
        id: go
      - name: Build
        run: go build -o build/main
      - name: Run
        run: ./build/main

# Path: .github\workflows\go.yml